server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cache Control for static assets (PWA)
    location ~* \.(?:cocos|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        root /usr/share/nginx/html;
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Cache Control for JS/CSS
    location ~* \.(?:css|js)$ {
        root /usr/share/nginx/html;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }

    # Disable cache for service worker and manifest files so updates are immediate
    location ~* \.(?:manifest|appcache|html|xml|json)$ {
        root /usr/share/nginx/html;
        expires -1;
        access_log off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
